# Generated by Django 2.0.1 on 2018-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField()),
                ('name', models.CharField(max_length=64, verbose_name='菜名')),
                ('category', models.CharField(max_length=64)),
                ('prime', models.FloatField(verbose_name='价格')),
                ('info', models.CharField(max_length=256, verbose_name='详细信息')),
                ('img_url', models.CharField(max_length=512, verbose_name='首页小图')),
                ('big_img_url', models.CharField(max_length=512, verbose_name='主页大图')),
                ('rate', models.IntegerField(default=0, verbose_name='好评率')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
            ],
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=128)),
                ('bucket', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=128)),
                ('img_height', models.IntegerField()),
                ('img_width', models.IntegerField()),
                ('file_format', models.CharField(max_length=32)),
                ('file_size', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('oss_key', models.CharField(max_length=512)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('bucket', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=128)),
                ('img_height', models.IntegerField()),
                ('img_width', models.IntegerField()),
                ('img_format', models.CharField(max_length=32)),
                ('img_size', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('oss_key', models.CharField(max_length=512)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('vendor_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
                ('order_items', models.CharField(default='[]', max_length=1024, verbose_name='订单项id列表')),
                ('prime', models.FloatField(default=0, verbose_name='价格')),
                ('prime_at_least', models.FloatField(verbose_name='最终用户支付价格')),
                ('create_time', models.DateTimeField(verbose_name='订单创建时间')),
                ('pay_time', models.DateTimeField(verbose_name='订单付款时间')),
                ('vendor_ensure_time', models.DateTimeField(verbose_name='商家确认时间')),
                ('ensure_time', models.DateTimeField(verbose_name='用户确认时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('school', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=1024)),
                ('receiver', models.CharField(max_length=32)),
                ('receiver_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('college', models.CharField(max_length=64)),
                ('register_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256, null=True)),
                ('in_canteen', models.BooleanField(default=False)),
                ('verify_condition', models.IntegerField(default=0)),
                ('register_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorAuthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(unique=True)),
                ('checked', models.BooleanField(default=False)),
                ('vendor_responsible_person_name', models.CharField(max_length=32, verbose_name='负责人名')),
                ('vendor_responsible_person_ID', models.CharField(max_length=64, verbose_name='负责人身份证')),
                ('vendor_responsible_person_ID_imageID', models.IntegerField(verbose_name='负责人身份证照片ID')),
                ('vendor_license_imageID', models.IntegerField(verbose_name='营业执照照片ID')),
            ],
        ),
        migrations.CreateModel(
            name='VendorBaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('condition', models.BooleanField(default=False, verbose_name='营业状态')),
                ('opening_time_day', models.CharField(max_length=64, verbose_name='营业时间')),
                ('logo_url', models.CharField(max_length=512, verbose_name='logoURL')),
                ('bulletin', models.CharField(max_length=1024, verbose_name='公告')),
                ('sales', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=32, verbose_name='分类')),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCodeCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=128)),
                ('relative_msg', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCodeStore',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('oss_url', models.CharField(max_length=1024)),
                ('local_path', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyMessage',
            fields=[
                ('request_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField()),
            ],
        ),
    ]
