# Generated by Django 2.0.2 on 2018-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('oss_key', models.CharField(max_length=512)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('college', models.CharField(max_length=64)),
                ('register_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32)),
                ('verify_condition', models.IntegerField(default=0)),
                ('register_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorBaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
                ('condition', models.BooleanField(default=False)),
                ('opening_time_day', models.CharField(max_length=64)),
                ('logo_url', models.CharField(max_length=512)),
                ('bulletin', models.CharField(max_length=1024)),
                ('category', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCodeCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=128)),
                ('relative_msg', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCodeStore',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('oss_url', models.CharField(max_length=1024)),
                ('local_path', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyMessage',
            fields=[
                ('request_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('send_time', models.DateTimeField()),
            ],
        ),
    ]
